sdf: ../sdfs/arena_flat_v0/sdf/arena_flat.sdf
spawn:
  loader: 0
  mode: !!python/object/apply:farms_core.model.options.SpawnMode
  - free
  pose:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  velocity:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  extras: {}
water:
  sdf: ../sdfs/arena_water_v0/sdf/arena_water.sdf
  drag: true
  buoyancy: true
  height: 0
  velocity:
  - 0
  - 0
  - 0
  viscosity: 1.0
  density: 800.0
  maps:
  - ''
  - ''
ground_height: -1.0
